# Generated by Django 4.2.7 on 2025-09-14 10:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0003_learningactivity_learningstreak_monthlyprogress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=20, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_completion', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Summary'), ('weekly', 'Weekly Summary'), ('never', 'Never')], default='immediate', help_text='When child completes a lesson', max_length=20)),
                ('streak_milestones', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Summary'), ('weekly', 'Weekly Summary'), ('never', 'Never')], default='immediate', help_text='When child achieves learning streaks', max_length=20)),
                ('inactivity_alerts', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Summary'), ('weekly', 'Weekly Summary'), ('never', 'Never')], default='daily', help_text="When child hasn't been active", max_length=20)),
                ('weekly_summary', models.BooleanField(default=True, help_text='Weekly progress summary')),
                ('monthly_summary', models.BooleanField(default=True, help_text='Monthly progress report')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(default=datetime.time(22, 0), help_text='No notifications after this time')),
                ('quiet_hours_end', models.TimeField(default=datetime.time(8, 0), help_text='No notifications before this time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('lesson_complete', 'Lesson Completed'), ('quiz_passed', 'Quiz Passed'), ('streak_milestone', 'Streak Milestone'), ('weekly_summary', 'Weekly Summary'), ('monthly_summary', 'Monthly Summary'), ('inactivity_alert', 'Inactivity Alert'), ('achievement', 'Achievement Unlocked'), ('goal_reached', 'Goal Reached'), ('recommendation', 'Learning Recommendation')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional notification data (scores, streaks, etc.)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('sent_via_app', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('child', models.ForeignKey(help_text='The child this notification is about', on_delete=django.db.models.deletion.CASCADE, related_name='parent_notifications', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.lesson')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent', 'status'], name='learning_pa_parent__730bc0_idx'), models.Index(fields=['child', 'notification_type'], name='learning_pa_child_i_15c648_idx'), models.Index(fields=['created_at'], name='learning_pa_created_74f3d0_idx')],
            },
        ),
    ]
