# Generated by Django 5.0.6 on 2025-09-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_parent_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='child_name',
            field=models.CharField(blank=True, help_text="Child's name for parents", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('nursery', 'Nursery'), ('kg', 'KG'), ('1', '1st Grade'), ('2', '2nd Grade'), ('3', '3rd Grade'), ('4', '4th Grade'), ('5', '5th Grade'), ('6', '6th Grade'), ('7', '7th Grade'), ('8', '8th Grade'), ('9', '9th Grade'), ('10', '10th Grade'), ('11', '11th Grade'), ('12', '12th Grade')], help_text='Grade/Class for students', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject taught for teachers', max_length=100, null=True),
        ),
    ]
